# fly.toml app configuration file generated for foodee-backoffice on 2025-03-07T10:32:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foodee-backoffice'
primary_region = 'otp'
console_command = '/code/manage.py shell'

[env]
  PORT = '8000'

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
