# Generated by Django 5.1 on 2025-01-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Місце", "verbose_name_plural": "Місця"},
        ),
    ]
