# Generated by Django 5.1 on 2024-11-14 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_category_options_category_parent_product_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "продукти"},
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={"verbose_name": "чек", "verbose_name_plural": "чеки"},
        ),
        migrations.AddField(
            model_name="receipt",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, verbose_name="назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=300, verbose_name="назва"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="number",
            field=models.PositiveIntegerField(default=True, null=True),
        ),
    ]
