# Generated by Django 5.1 on 2024-11-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_remove_productitem_product_productitem_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "ordering": ("created_at",),
                "verbose_name": "чек",
                "verbose_name_plural": "чеки",
            },
        ),
    ]
