# Generated by Django 5.1 on 2024-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_receipt_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="updated_at",
            field=models.DateTimeField(default="2010-01-01 22:22"),
            preserve_default=False,
        ),
    ]
