# Generated by Django 5.1 on 2024-12-03 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_receipt_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="дата оновлення"
            ),
        ),
    ]
