# Generated by Django 5.1 on 2025-01-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_receipt_place"),
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="place.place",
                verbose_name="місце",
            ),
        ),
    ]
