# Generated by Django 5.1 on 2025-01-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_receipt_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="payment_metnod",
            field=models.CharField(
                choices=[("CARD", "Картка"), ("CASH", "Готівка")],
                default="CARD",
                max_length=10,
            ),
        ),
    ]
