# Generated by Django 5.1 on 2025-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_remove_productitem_price_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="назва"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="номер"
            ),
        ),
    ]
