# Generated by Django 5.1 on 2025-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_productitem_name_alter_receipt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Відкритий"), ("CLOSED", "Зaкритий")],
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
