# Generated by Django 5.1 on 2025-03-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_receipt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CARD", "Картка"),
                    ("CASH", "Готівка"),
                    ("CARD_TRANSFER", "Переказ на картку"),
                ],
                default="CARD",
                max_length=50,
            ),
        ),
    ]
