# Generated by Django 5.1 on 2025-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_alter_receipt_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
