# Generated by Django 5.1 on 2025-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_productitem_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveSmallIntegerField(default=100, verbose_name="порядок"),
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.PositiveSmallIntegerField(default=100, verbose_name="порядок"),
        ),
    ]
